### ISSUE TITLE
[IDEA] Collaboration for AudioAlign "port"

### ISSUE THREAD

**Issue by MarcoRavich** [krsch/audio-alignment#1]
Hi there, seems that your scripts does something like AudioAlign:

https://github.com/protyposis/AudioAlign

Unfortunally it's not multiplatform (Windows only), so it would be great to establish some kind of collaboration in order to obtain a platform-indipendent Sync Library.

Hope that inspires !

**Comment by krsch** [comment]
AudioAlign is written in C# while my scripts are in python. Though it would be great to embed my scripts into some good GUI for better automation and ease of use, I'm not interested in doing it for a Windows-only application as my main platform is Linux.
Nevertheless, thanks for the link! Maybe I will decide to create a similar GUI.

**Comment by MarcoRavich** [comment]
Well, yes, the idea was exactly to make AudioAlign multiplatform (in other words, to "port" their C# code to C/C++) !
